### PR TITLE
Add FTP import support

### PR DESCRIPTION
**Pull request by hallipr**
- Add ProtectedData based encryption utility
- Add PackageReference to FluentFTP library (MIT License)
- Add FTP credentials collection form
- Add logic to Form1.cs to conditionally display FTP credentials popup
- Add support for multi-server creature status update and cross server creature movement

### CODE REVIEW

**Comment by cadon** [comment]
Thanks for the commit! I'll check it after the holidays.

**Comment by hallipr** [comment]
conflicts resolved

**Comment by hallipr** [comment]
Rebased, conflicts resolved.
I also adjusted the multi-server import to prevent it from marking creatures imported on other servers as Unavailable.  If importing creatures from ServerX, only creatures with server == "ServerX" should be marked as unavailable if they're not in the serverX list.

**Comment by hallipr** [comment]
Rebased, conflicts resolved.

I moved the added FTP toward the middle of the settings file to avoid merge conflicts with other added settings.  You may want to alphabetize the members of heavily modified files to avoid frequent conflicts at the end of the file.

**Comment by hallipr** [comment]
Awesome.  Thanks

**Pull request merged**
