### PR TITLE
Timer custom sounds

### PR DESCRIPTION
**Pull request by maxime-paquatte**
Allow to select custom sound file from "sounds" directory

### CODE REVIEW

**Comment by cadon** [comment]
Hi, thanks for that addition!
By looking through the code I noticed you deleted the control `dhmsInputTimer` in `TimerControl`. Was this intentional? I think that control gives an easy way to create a timer with a set time without the need of calculating the time the timer will end.

**Comment by maxime-paquatte** [comment]
Hi,

I did not delete the control. I recieved NullRefException and I did not
take the time to check why, so I juste add  if(dhmsInputTimer != null)
Of course you can remove this line.

**Comment by cadon** [comment]
In the designer-file the control is deleted in this pull request, see e.g. [1](https://github.com/cadon/ARKStatsExtractor/pull/931/files#diff-5a6cee1068d27511283924248709135cL45) or [2](https://github.com/cadon/ARKStatsExtractor/pull/931/files#diff-5a6cee1068d27511283924248709135cL180) . If you readd it, I can merge the pull request.

**Comment by maxime-paquatte** [comment]
ok, I dont know what appened, sorry.

**Pull request merged**
