### PR TITLE
Add a species column to the ListViewLibrary and a an option to remove the grouping of the species (this allow for an ordering on the name of the creatures)

### PR DESCRIPTION
**Pull request by EmkioA**
This help me to order the creatures by Name as shown here :

image

Will coding this i find a bug with the ShowMale and ShowFemale filter, i fixed it.

### CODE REVIEW

**Comment by EmkioA** [comment]
Still learning the fork/pull request, dont know why my 3 comit are into the same...

But the third is from the request #1012 

Here is the new feature :
image

**Comment by EmkioA** [comment]
i think their is a problem with the translations system for those new text.

**Comment by EmkioA** [comment]
My bad for those last commit, im learning :( i think i must use branch to fix this problem and having multiple pull request for multiple feature?

**Comment by cadon** [comment]
Thanks for these additions and the fix regarding the female/male view! One PR per feature is indeed better. You can read about pull requests for example here: https://www.atlassian.com/git/tutorials/making-a-pull-request. No worries, though.

**Pull request merged**
