### PR TITLE
Gaiamod

### PR DESCRIPTION
**Pull request by Inkraja**
**Mod title:** Gaia
**Author/Modowner:** Prome / |SE|prome
**Mod id:** [1125442531 ](http://steamcommunity.com/sharedfiles/filedetails/?id=1125442531)
**Website:** [https://gaia.prome.org/](https://gaia.prome.org/)

### CODE REVIEW

**Comment by cadon** [comment]
Thanks for the data! I'll include it in the next release.

**Comment by Inkraja** [comment]
blame by myself, fix is there: 158be269b22c59ead1da4605ee33a97901cb03b2

open: need to check the griffin stats

**Comment by cadon** [comment]
yes, saw that syntax error and fixed it already. I'll wait for the griffin before merging it then.

**Comment by Inkraja** [comment]
need to talk with prome first, the issue is deeper in the stats

**Pull request merged**
