### PR TITLE
New command-line library updater (from savegames)

### PR DESCRIPTION
**Pull request by coldino**
New command-line tool reads from savegames and updates libraries. It is designed to run on servers directly. See `ArkBreedingSaveExtractor.exe --help` output below for detailed info.

Reverts .Net Framework minimum requirement of ASB to v4.6.1 in order to more easily support use on Mono and give a possible route to .Net Core migration in future. Suggest the installer should continue to offer v4.7.2.

```
Usage: ArkBreedingSaveExtractor [ -h|--help ] [ --version ] [ -q|--quiet ] [ -c|--create ] [ -t|--tribe T ] [ -n|--no-status ] [ -m|--mod MOD ] [ -e|--exceptions ] ARKFILE SERVERNAME LIBRARY

 Updates an ASB library file with creatures from a saved Ark.

Positional Arguments:
 ARKFILE           The .ark file to read from.
 SERVERNAME        Name to use for the server field in creatures.
 LIBRARY           The ASB library .xml file to update.

Optional Arguments:
 -c, --create      Create the library if it doesn't already exist.
 -e, --exceptions  Show full exceptions on error.
 -h, --help        Display this help document.
 -m, --mod         Load mod support from 'json/MOD.json' (can be supplied more than once).
 -n, --no-status   Do not update the status of creatures (use if importing from multiple arks).
 -q, --quiet       Don't show stats and results.
 -t, --tribe       Filter and only read creatures from the named tribe.
 --version         Displays the version of the current executable.
```

### CODE REVIEW

**Comment by coldino** [comment]
This needs testing by some server owners before merging in.

**Comment by ToeiRei** [comment]
Extensive testing and debugging done on debian/mono stable

**Comment by coldino** [comment]
For this to run on a server it requires:
```
ARK Smart Breeding.exe
ArkBreedingSaveExtractor.exe
SavegameToolkit.dll
Newtonsoft.Json.dll
clipr.dll
json/
```

Run it using mono, e.g.:
```
$ mono ArkBreedingSaveExtractor.exe --help
```

I've attached a build with debug symbols included for anyone who wants to test it now:
[Debug.zip](https://github.com/cadon/ARKStatsExtractor/files/2975479/Debug.zip)

**Comment by coldino** [comment]
Updated to latest ASB. Attached an updated build for anyone testing it:
[Debug.zip](https://github.com/cadon/ARKStatsExtractor/files/3019203/Debug.zip)

**Comment by ntrixter** [comment]
Are there plans to update the command line tool to use the new .asb file format?

**Comment by coldino** [comment]
I'd like to, yes, but this is going to take some time.

**Comment by coldino** [comment]
Sadly this is going to be a significant change due to the new mod support and the need to keep all the relevant values files updated. I'm going to have to close this pull request and open a fresh one when we've figured out how to achieve it.

**Pull request closed without merging**
