### PR TITLE
Add of 3 new column into the Library (Father Mutation and Mother Muta…

### PR DESCRIPTION
**Pull request by EmkioA**
Add of 3 new column into the Library (Father Mutation (FMu) and Mother Mutation (MMu) (spliting the Mutation column) and Level (actual level of the creature))

### CODE REVIEW

**Comment by cadon** [comment]
Thanks for the contribution, but I see it like VolatilePulse. More columns mean more needed computing power, so additional columns should be important for users.
Regarding the splitting of maternal and paternal mutations, despite multiple requests of making that more visible in ASB (I was finally ok with adding tooltips that show these in the breeding planner), I have never seen any useful information in that. Many player think mutations can happen if one of the mutation parts is less than 20, but that's not true. The only thing one need to know about the mutation counter of a creature is the sum of maternal and paternal mutations.
Regarding the total level of creature, I see that this may be useful for some players after breeding, but so far there was no request for that. ASB is mainly about breeding, and for that the total level is not needed.
Because of that, I'll not merge the pull request. I'm looking forward to other changes you propose, though.

**Comment by EmkioA** [comment]
No problem :)  i understand.  That was just helpfull for me :)  If you want me to focus on something just let me know.


About mutation : 

I saw rex with 170pts in damage after mutation, How can people manage to climb those that up?  I think, till you have one side < 20 there will be some mutation.  let say you have 20/20 0/20 if you mutate  you have 20/20 1/20 and after that you transfer the mutation to a child, 21/20 0/20 and you continue... 60/20 0/20 ...  (50 base + 60 mutations = 170pts) but, you have ½ chance of having a mutation since one side is "full".  This is why i think its a good idea to split the value.

This post explain my understanding of the breeding:
https://www.reddit.com/r/playark/comments/66n962/mutations_and_you_a_guide_on_breeding_mutations/

This guide is soooo long : https://www.youtube.com/watch?v=wL4fDTRg4Ig
but look at the 1:39:00 - 1:41:30, she show how baby receive the total of mutation from its parents.  

If you have more infos thank you to share it :)

**Comment by coldino** [comment]
Your understanding of what limits mutations is not correct. The only values ever considered are the **sum** of the two mutation counters for the mother, and the **sum** of the two mutation counters for the father.

The guide you link to - Mutations and You - is accurate and is exactly what we recommend to users with queries, but it seems you are misinterpreting it. If you need a different style of explanation try this - it's a C# representation of the disassembly of the mutation code:
https://www.reddit.com/r/playark/comments/6gsk84/breeding_and_mutation_probabilities_from/

As for future work possibilities, please join us on Discord where it's much easier to discuss options!

**Comment by EmkioA** [comment]
Thank you! i will take a look :)

**Comment by EmkioA** [comment]
OK i see what you mean!

The count of where is the mutation is from is not relevant for FUTURE breeding! 
Actualy only parents with mutation < 20 can mutate a stats.  So if the dyno is >= 20 (with both side) it is not good for future mutation.

But what you missed from the code is that :  if one parent is under 20, it can mutate the other parent stat!  As the code chose the stats BEFORE checking for adding a mutation!

first it pick wich stat it will give from the father or the mother (this or withMate)
           // Inherited stats (there is a 55/45 chance to inherit the best stat)
           ...
After that it tie the mutation to one side, and level up the stat if the mutation is < 20 for this side 
            // Random mutations
            ...
            // Update offspring
            ...



So, a male with 20/20 (str 50)  and a female with 0/20 (str 40) can give a new baby with the male stat + 2pts (str 52), and have 20/20 1/20 on mutation counters!

But that implies that if one parent is >=20 the wanted mutation (the highest stat) is 0.55000001f; less chance to arrive than from a couple with both side < 20.

What you think about it?

**Comment by cadon** [comment]
Yes, that sounds correct.
In the breeding planner you can set the mutation limit to 19, so only creatures will be displayed that can still contribute to mutations. If you enable the checkbox `One partner may have more mutations` all pairs will be considered where at least one partner has less than 20 mutations.

**Comment by EmkioA** [comment]
Thank you, it realy confirm my tought on the mutation process.  I was sceptic about one side mutating the other side.

**Pull request closed without merging**
